version: '2'
services:
  scout2:
    container_name: scout2
    image: scout2
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./scout2-report:/app/scout2-report
      - $HOME/.aws:/root/.aws

  scout2-web:
    container_name: scout2-web
    image: nginx:alpine
    volumes:
      - ./scout2-report:/usr/share/nginx/html:ro
    ports:
      - '8000:80'

